### PR TITLE
error toasts frontend

### LINKED ISSUE #456: Handle different kind of error while logging In
Deliverable:
We need to handle the follow errors and show relevant message to the user using `Toast`
1. Backend server not runing
2. Status 400 - Unauthorised
3. For rest, show `Something went wrong`

P.S - This issue can only be worked on after closing #454

### PR DESCRIPTION
**Pull request by ashuvssut**
Closes #456 

Added error toasts for
- [x] Backend server not runinng
- [x] Status 400 - Unauthorised
- [x] For rest, show "Something went wrong"

EXTRA
- made minor changes to toast.jsx ( added severity prop)

--------------------------

_I have participated in GSSOC_

### CODE REVIEW

**Comment by Kajol-Kumari** [comment]
Hey @ashuvssut can we please add a success-toast after successful login?

**Comment by ashuvssut** [comment]
@Kajol-Kumari , toast added

File: frontend/src/pages/Admin/Components/Dashboard/Dashboard.jsx [hunk 1]
```diff
@@ -42,22 +59,22 @@ export const Dashboard = (props) => {
...
               <h4> {d.name} </h4>
             </div>
-            <div className={style["content"]}>
-              Get all your {d.name} related details here!
-            </div>
+            <div className={style["content"]}>Get all your {d.name} related details here!</div>
           </div>
         ))}
       </div>
+      <SimpleToast
```
Comment (Kajol-Kumari) [inline frontend/src/pages/Admin/Components/Dashboard/Dashboard.jsx:72]: Hey @ashuvssut adding it here, it will show the toast message every-time we visit the `dashboard` instead, we need it only when the user clicks on `submit` button of the login form and gets successfully logged in

Comment (ashuvssut) [reply frontend/src/pages/Admin/Components/Dashboard/Dashboard.jsx:74]: @Kajol-Kumari , done!

**Review by Kajol-Kumari — APPROVED** [review]
Thanks for incorporating the suggested changes
LGTM :+1:
