### PR TITLE
[Frontend] Integrate the Delete Team Member API with frontend Fixed

### LINKED ISSUE #894: [Frontend] Integrate the Delete Team Member API with frontend
## Description

- [ ] The delete button is useless rn, integrate the [delete team member api](https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/teamMember/deleteTeamMember.js) with it so that admin can delete the redundantly added members.
- [ ] The image isn't appearing in the fetched member list, fix it.

 
Screenshot 2024-05-16 at 12 05 09 PM

### PR DESCRIPTION
**Pull request by Hemu21**
## Issue that this pull request solves
[Issue Link](https://github.com/HITK-TECH-Community/Community-Website/issues/894) resolve #894 

 Closes: #894 

### Brief description of what is fixed or changed

I found the bug of multer and fixed it and made that image display is fine. and added delete feature. and a small thing related to manage Q&A that is also fixed. Now Images display fine and delete works fine and manage q&a also.

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

kajolcheck

### CODE REVIEW

**Comment by Hemu21** [comment]
@Kajol-Kumari  can you please check and merge it.

File: frontend/src/pages/Admin/Components/Faq/Q&A/ManageQ&A/ManageQ&A.jsx [hunk 1]
```diff
@@ -163,7 +163,7 @@ export function Manageqa({ setTab, qId }) {
               </div>
             </div>
 
-            {ans?.length !== 0 ? (
```
Comment (Kajol-Kumari) [inline frontend/src/pages/Admin/Components/Faq/Q&A/ManageQ&A/ManageQ&A.jsx:166]: nice catch!

**Review by Kajol-Kumari — APPROVED** [review]
LGTM 👍
