### PR TITLE
[BUG] post testimonials backend Fixed

### LINKED ISSUE #1054: [BUG] post testimonials backend
**Describe the bug**
- [ ] We are using to save in image using multer. In backend the post testimonials is not used the multer. This leads to ask user to ask url from frontend. that will reduce user experience. 
- [ ] along with backend update we need to update the frontend for posting and getting of the image and data. 
- [ ] Need to update the image display process in frontend. 

Note: This issue includes both frontend and backend changes.

**Priority**
High

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
yes

### PR DESCRIPTION
**Pull request by Hemu21**
## Issue that this pull request solves

[Issue Link](https://github.com/HITK-TECH-Community/Community-Website/issues/1054) resolve #1054 
 Closes: #1054 

### Brief description of what is fixed or changed
- [x] We are using to save in image using multer. In backend the post testimonials is not used the multer. This leads to ask user to ask url from frontend. that will reduce user experience. 
- [x] along with backend update we need to update the frontend for posting and getting of the image and data. 
- [x] Need to update the image display process in frontend. 

Now testimonial image saving and display is working fine.

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

### CODE REVIEW

**Comment by Hemu21** [comment]
@Kajol-Kumari can you please check and merge it.

**Review by Kajol-Kumari — COMMENTED** [review]
minor comment

**Comment by Hemu21** [comment]
@Kajol-Kumari  can you please tell what are the minor comments

File: frontend/src/pages/Admin/Components/Testimonial/AddTestimonial/AddTestimonial.jsx [hunk 1]
```diff
@@ -11,7 +11,7 @@ export function AddTestimonial() {
     name: "",
     position: "",
     company: "",
-    image: "https://i.pinimg.com/originals/f4/cd/d8/f4cdd85c50e44aa59a303fb163ff90f8.jpg",
+    image: "",
```
Comment (Kajol-Kumari) [inline frontend/src/pages/Admin/Components/Testimonial/AddTestimonial/AddTestimonial.jsx:14]: There should be a default image incase admin doesn’t provide it ‘coz this will appear on home page

Comment (Hemu21) [reply frontend/src/pages/Admin/Components/Testimonial/AddTestimonial/AddTestimonial.jsx:14]: @Kajol-Kumari  yes it is implemented.

File: frontend/src/service/Testimonial.jsx [hunk 2]
```diff
@@ -13,7 +13,20 @@ async function getTestimonials(setTestimonials, setToast) {
...
+        let formattedPath = item.image?.replace(/\\/g, "/");
+        if (formattedPath?.startsWith("uploads/")) {
+          formattedPath = formattedPath.replace("uploads/", "");
+          if (formattedPath) {
+            formattedPath = `${END_POINT}/${formattedPath}`;
+          }
+        }else{
+          formattedPath = "./images/testimonialImg.png";
+        }
+        _data[index].image = formattedPath;
```
Comment (Hemu21) [inline frontend/src/service/Testimonial.jsx:27]: @Kajol-Kumari  This is the function we used to get data. here I made small chage if image exist. we use that url else we use default image a url.

**Comment by Hemu21** [comment]
@Kajol-Kumari  I had made it as if user provide the image we use it and display it. if user doesn't provide then no need to save default. instead we can show them default in frontend.  I check it is working. you can check in the preview you can see the default images.

**Review by Kajol-Kumari — APPROVED** [review]
